// New:
import GAppsIcons from "../../../assets/icons/google_apps"

export const GApps = [
    { id: "search", name: "Search", icon: GAppsIcons.gsearch, url: "https://www.google.com" },
    { id: "gemini", name: "Gemini", icon: GAppsIcons.gemini, url: "https://gemini.google.com/app" },
    { id: "gmail", name: "Gmail", icon: GAppsIcons.gmail, url: "https://mail.google.com" },
    { id: "drive", name: "Drive", icon: GAppsIcons.drive, url: "https://drive.google.com" },
    { id: "youtube", name: "Youtube", icon: GAppsIcons.youtube, url: "https://www.youtube.com" },
    { id: "ytmusic", name: "YTMusic", icon: GAppsIcons.ytmusic, url: "https://music.youtube.com" },
    { id: "keep1", name: "Keep", icon: GAppsIcons.keeps, url: "https://keep.google.com" },
    { id: "forms1", name: "Forms", icon: GAppsIcons.forms, url: "https://docs.google.com/forms" },
    { id: "slides", name: "Slides", icon: GAppsIcons.slides, url: "https://docs.google.com/presentation" },
    { id: "tasks", name: "Tasks", icon: GAppsIcons.tasks, url: "https://tasks.google.com" },
    { id: "maps1", name: "Maps", icon: GAppsIcons.maps, url: "https://www.google.com/maps" },
    { id: "calendar", name: "Calendar", icon: GAppsIcons.calendar, url: "https://calendar.google.com" },
    { id: "earth", name: "Earth", icon: GAppsIcons.earth, url: "https://earth.google.com" },
    { id: "books", name: "Books", icon: GAppsIcons.books, url: "https://books.google.com" },
    { id: "docs", name: "Docs", icon: GAppsIcons.docs, url: "https://docs.google.com/document" },
    { id: "finance", name: "Finance", icon: GAppsIcons.finance, url: "https://finance.google.com" },
    { id: "forms2", name: "Forms", icon: GAppsIcons.forms, url: "https://docs.google.com/forms" },
    { id: "keep2", name: "Keeps", icon: GAppsIcons.keeps, url: "https://keep.google.com" },
    { id: "maps2", name: "Maps", icon: GAppsIcons.maps, url: "https://www.google.com/maps" },
    { id: "meet", name: "Meet", icon: GAppsIcons.meet, url: "https://meet.google.com" },
    { id: "news", name: "News", icon: GAppsIcons.news, url: "https://news.google.com" },
    { id: "password", name: "Password", icon: GAppsIcons.password, url: "https://passwords.google.com" },
    { id: "photos", name: "Photos", icon: GAppsIcons.photos, url: "https://photos.google.com" },
    { id: "scholar", name: "Scholar", icon: GAppsIcons.scholar, url: "https://scholar.google.com" },
    { id: "sheets", name: "Sheets", icon: GAppsIcons.sheets, url: "https://docs.google.com/spreadsheets" },
    { id: "shopping", name: "Shopping", icon: GAppsIcons.shopping, url: "https://shopping.google.com" },
    { id: "sites", name: "Sites", icon: GAppsIcons.sites, url: "https://sites.google.com" },
    { id: "translate", name: "Translate", icon: GAppsIcons.translate, url: "https://translate.google.com" },
    { id: "webstore", name: "Webstore", icon: GAppsIcons.webstore, url: "https://chrome.google.com/webstore" },
    { id: "travel", name: "Travel", icon: GAppsIcons.travel, url: "https://www.google.com/travel" },
    { id: "blogger", name: "Blogger", icon: GAppsIcons.blogger, url: "https://www.blogger.com" }
];